### ISSUE TITLE
Segmentation Labels

### ISSUE THREAD

**Issue by smcch** [NeuroAI-HD/HD-GLIO#12]
Thank you to the author for providing this outstanding tool. I was able to successfully run the code on several preoperative MRI scans. However, when I checked the segmentation file, I noticed that I only obtained two labels: Contrast enhancing tumor and T2/FLAIR signal alteration. Can you explain why this might be happening?

Operating System: Ubuntu 20.04.4 LTS - WSL 2
Python Version: 3.7

Thanks!

**Comment by FabianIsensee** [comment]
Hi,
this is because the model was only trained with those two labels. If you need a label for necrosis as well, I can recommend our docker for BraTS2020: https://hub.docker.com/r/fabianisensee/isen2020
Read also: https://github.com/BraTS/Instructions
(unfortunately very outdated with docker links, but instructions are OK)
Best,
Fabian

**Comment by smcch** [comment]
I will definitely test out your Docker. Thank you for your quick response. Best regards
